---
- name: "create user (generic)"
  hosts: all
  become: yes
  vars:
    # empty default (will be replaced through  inventory.yml)
    username: ""
    user_password_hash: ""
    user_ssh_key: ""
    delete_user_first: false
  tasks:
    - name: "Delete '{{ username }}' (if delete_user_first=true)"
      ansible.builtin.user:
        name: "{{ username }}"
        state: absent
        remove: yes
      when: delete_user_first

    - name: "Adduser '{{ username }}'"
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ user_password_hash }}"
        shell: /bin/bash
        home: "/home/{{ username }}"
        groups: sudo
        append: yes
        state: present
        create_home: yes
        comment: "Admin Account for {{ username }}"

    - name: "Add SSH-Key for '{{ username }}' (optional)"
      ansible.builtin.authorized_key:
        user: "{{ username }}"
        key: "{{ user_ssh_key }}"
        state: present
      when: user_ssh_key | length > 0  # Führt die Aufgabe nur aus, wenn user_ssh_key nicht leer ist

    - name: "Allow sudo with NO password for '{{ username }}' (optional)"
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
      when: "'sudo' in group_names"
